# Generated by Django 3.2 on 2024-09-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='user_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
